=== api-evangelist/spacex/json-schema/spacex-history-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://api-evangelist.github.io/spacex/json-schema/spacex-history-schema.json",
  "title": "SpaceX HistoryEvent",
  "description": "A historical SpaceX event. Derived from the r-spacex/SpaceX-API mongoose model.",
  "x-schema-source": "documentation",
  "x-source-url": "https://github.com/r-spacex/SpaceX-API/tree/master/docs",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string",
      "nullable": true
    },
    "event_date_utc": {
      "type": "string",
      "nullable": true,
      "format": "date-time"
    },
    "event_date_unix": {
      "type": "integer",
      "nullable": true
    },
    "details": {
      "type": "string",
      "nullable": true
    },
    "links": {
      "type": "object",
      "properties": {
        "article": {
          "type": "string",
          "nullable": true,
          "format": "uri"
        }
      }
    }
  }
}

=== api-evangelist/spacex/examples/spacex-gethistoryevent-example.json
{
  "links": {
    "article": "http://www.spacex.com/news/2013/02/11/flight-4-launch-update-0"
  },
  "title": "Falcon reaches Earth orbit",
  "event_date_utc": "2008-09-28T23:15:00Z",
  "event_date_unix": 1222643700,
  "details": "Falcon 1 becomes the first privately developed liquid-fuel rocket to reach Earth orbit.",
  "id": "5f6fb2cfdcfdf403df37971e"
}
